import { Quest } from './QuestTypes';

const now = (): string => new Date().toISOString();

export const getSeedQuests = (): Quest[] => [
  {
    id: 'FORTRESS-INTRO-001',
    kind: 'tutorial',
    title: 'Light the Town Hall',
    description: 'Review your I-AM profile and acknowledge your current path.',
    requirements: [],
    rewards: {
      xp: [{ domain: 'coherence', amount: 10 }],
    },
    buildingId: 'TownHall',
    offeredBy: 'Tyme',
    status: 'available',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'WORKSHOP-START-001',
    kind: 'xp-milestone',
    title: 'Craft Your First Blueprint',
    description: 'Use the Workshop to run a craft simulation.',
    requirements: [{ type: 'xp-domain-min', domain: 'craft', value: 5 }],
    rewards: {
      xp: [{ domain: 'craft', amount: 15 }],
    },
    buildingId: 'Workshop',
    offeredBy: 'Fabricator',
    status: 'available',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'LIBRARY-START-001',
    kind: 'story',
    title: 'Decode the First Tome',
    description: 'Consult the Library and parse a knowledge thread.',
    requirements: [{ type: 'xp-domain-min', domain: 'knowledge', value: 5 }],
    rewards: {
      xp: [{ domain: 'knowledge', amount: 12 }],
      traits: [{ traitId: 'scholarship', levels: 1 }],
    },
    buildingId: 'Library',
    offeredBy: 'Archivist',
    status: 'available',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'OBSERVATORY-START-001',
    kind: 'talos',
    title: 'Trace the Skybridge',
    description: 'Run a scan in the Observatory and listen for Talos echoes.',
    requirements: [{ type: 'xp-domain-min', domain: 'insight', value: 5 }],
    rewards: {
      xp: [{ domain: 'insight', amount: 12 }],
      traits: [{ traitId: 'vision', levels: 1 }],
    },
    buildingId: 'Observatory',
    offeredBy: 'Tyme',
    status: 'available',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'GARDENS-START-001',
    kind: 'trait-evolution',
    title: 'Breathe with the Nexus',
    description: 'Meditate in the Gardens until coherence settles.',
    requirements: [{ type: 'xp-domain-min', domain: 'coherence', value: 5 }],
    rewards: {
      xp: [{ domain: 'coherence', amount: 12 }],
      traits: [{ traitId: 'presence', levels: 1 }],
    },
    buildingId: 'Gardens',
    offeredBy: 'Harmonia',
    status: 'available',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'GUARDTOWER-START-001',
    kind: 'building-upgrade',
    title: 'Secure the Battlements',
    description: 'Run a boundary scan and log the perimeter.',
    requirements: [{ type: 'xp-domain-min', domain: 'integrity', value: 5 }],
    rewards: {
      xp: [{ domain: 'integrity', amount: 12 }],
      traits: [{ traitId: 'boundaries', levels: 1 }],
    },
    buildingId: 'GuardTower',
    offeredBy: 'Guardian',
    status: 'available',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'PORTALGATE-START-001',
    kind: 'story',
    title: 'Step Through the Gate',
    description: 'Visit the PortalGate and announce your next mission.',
    requirements: [{ type: 'building-unlocked', buildingId: 'PortalGate', value: 1 }],
    rewards: {
      xp: [{ domain: 'quest', amount: 20 }],
      unlockBuildings: ['PortalGate'],
    },
    buildingId: 'PortalGate',
    offeredBy: 'Initiate',
    status: 'available',
    createdAt: now(),
    updatedAt: now(),
  },
];
